### ISSUE TITLE
Question 동작 방식과 관련해서 질문드립니다.

### ISSUE THREAD

**Issue by jpoh281** [ChiwanAhn/petstagram_provider_pattern#2]
**질문내용을 입력해 주세요**

1. 똑같은 클래스명을 가진 home_screen과 homeScreen이 두가지 있는 이유가 궁금합니다.
2. MVVM을 보고 있는데 생소해서 코드의 작동방식을 이해하기가 조금 어렵습니다.
제가 코드를 이해했을 때 noti -> repo -> api_service -> repo -> noti로 이런 식으로 동작하는게 맞을까요??
3. api에 퓨처 딜레이를 넣으신 이유가 궁금합니다.
4. export해놓으면 특별히 따로 import를 안해줘도 되는건가요?? 
**참고할 코드를 입력해 주세요**

```
class PostApiService implements BasePostApiService {
  Future<List<Post>> listPost() async {
    await Future.delayed(Duration(milliseconds: 500));
    return await Future.value(
      List.generate(
        1,
        (index) => Post(
          id: 'p-$index',
          author: User(
            id: 'u-$index',
            username: 'bibber_',
          ),
          imageUrls: [
            'https://images.unsplash.com/photo-1594399981502-94a5079e2142?ixlib=rb-1.2.1&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=1080&fit=max'
          ],
          description: '코바늘',
        ),
      ),
    );
  }
}
```

**Comment by ChiwanAhn** [comment]
1. 알 수 없는 이유로 파일이 복제된것 같네요 :) 수정드리겠습니다

2. repo라는 부분을 조금 간결하게 만들 예정입니다 예상하신 방식이 맞습니다

3. 실제 API서버 없이 제작이 되어있기 때문에 추후 로딩부분을 구현하기 위해 딜레이가 있는 것 처럼 구현했습니다

4. export만 하셔도 다른 파일에서 참고할 수 있습니다 

Thank you 👍
